"""Generate independent GFX-009 setup/coverage vectors for the SV testbench."""

from __future__ import annotations

import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from sw.reference.gfx_primitives import Q4Point, triangle_coverage, edge_is_top_left


OUT = ROOT / "tb/tests/raster_walk_vectors.svh"


def setup_for(vertices: tuple[Q4Point, Q4Point, Q4Point]) -> dict[str, object]:
    v0, v1, v2 = vertices
    edges = ((v0, v1), (v1, v2), (v2, v0))
    deltas = tuple((b.x - a.x, b.y - a.y) for a, b in edges)
    coverage = triangle_coverage(vertices)
    assert coverage.classification.value == "accepted"
    assert not coverage.bbox.is_empty
    assert coverage.bbox.xmin is not None
    assert coverage.bbox.xmax is not None
    assert coverage.bbox.ymin is not None
    assert coverage.bbox.ymax is not None
    xmin, xmax = coverage.bbox.xmin, coverage.bbox.xmax
    ymin, ymax = coverage.bbox.ymin, coverage.bbox.ymax
    sample_x, sample_y = (xmin << 4) + 8, (ymin << 4) + 8
    initials = tuple(
        (b.x - a.x) * (sample_y - a.y) - (b.y - a.y) * (sample_x - a.x)
        for a, b in edges
    )
    steps = tuple(
        (-(dy << 4), dx << 4) for dx, dy in deltas
    )
    top = tuple(edge_is_top_left(a, b) for a, b in edges)
    return {
        "vertices": vertices,
        "tag": len(vertices) + xmin + (ymin << 4),
        "xmin": xmin,
        "xmax": xmax,
        "ymin": ymin,
        "ymax": ymax,
        "deltas": deltas,
        "top": top,
        "steps": steps,
        "initials": initials,
        "covered": coverage.covered,
        "candidates": coverage.candidates,
    }


def sv32(value: int) -> str:
    return f"32'sh{value & 0xffffffff:08x}"


def sv42(value: int) -> str:
    return f"42'sh{value & ((1 << 42) - 1):011x}"


def attributes_for(index: int, rng: random.Random) -> dict[str, tuple[int, int, int]]:
    extrema = [0, 1, (1 << 31) - 1, -(1 << 31), -1]
    if index == 0:
        return {
            "r": ((1 << 31) - 1, (1 << 31) - 1, 1),
            "g": (-(1 << 31), -(1 << 31), -1),
            "b": (-1, 1, (1 << 31) - 1),
            "z": (0, 0, 1),
        }
    if index < len(extrema):
        return {
            channel: (extrema[(index + offset) % len(extrema)],
                      extrema[(index + offset + 1) % len(extrema)],
                      extrema[(index + offset + 2) % len(extrema)])
            for offset, channel in enumerate(("r", "g", "b", "z"))
        }
    return {
        channel: (rng.randint(-(1 << 31), (1 << 31) - 1),
                  rng.randint(-(1 << 31), (1 << 31) - 1),
                  rng.randint(-(1 << 31), (1 << 31) - 1))
        for channel in ("r", "g", "b", "z")
    }


def generate() -> None:
    directed = [
        ((Q4Point(16, 16), Q4Point(160, 16), Q4Point(16, 160))),  # ordinary
        ((Q4Point(8, 8), Q4Point(320, 8), Q4Point(8, 320))),  # large
        ((Q4Point(16, 16), Q4Point(160, 16), Q4Point(88, 112))),  # flat top
        ((Q4Point(16, 16), Q4Point(160, 112), Q4Point(16, 112))),  # flat bottom
        ((Q4Point(16, 16), Q4Point(64, 17), Q4Point(16, 32))),  # thin
        ((Q4Point(8, 8), Q4Point(9, 8), Q4Point(8, 24))),  # tiny/subpixel
        ((Q4Point(0, 0), Q4Point(80, 0), Q4Point(0, 80))),  # left/top
        ((Q4Point(5104, 0), Q4Point(5120, 0), Q4Point(5120, 16))),  # right
        ((Q4Point(0, 3824), Q4Point(16, 3840), Q4Point(0, 3840))),  # bottom
        ((Q4Point(0, 0), Q4Point(16, 0), Q4Point(0, 9))),  # positive, zero cover
        ((Q4Point(8, 8), Q4Point(24, 8), Q4Point(8, 24))),  # one-pixel bbox
        ((Q4Point(128, 128), Q4Point(320, 128), Q4Point(128, 320))),  # shared rectangle A
        ((Q4Point(320, 128), Q4Point(320, 320), Q4Point(128, 320))),  # shared rectangle B
    ]
    rng = random.Random(0x9009)
    attr_rng = random.Random(0xA010)
    cases: list[dict[str, object]] = []
    for vertices in directed:
        case = setup_for(vertices)
        case["attributes"] = attributes_for(len(cases), attr_rng)
        cases.append(case)

    while len(cases) < 48:
        vertices = tuple(
            Q4Point(rng.randrange(0, 1025), rng.randrange(0, 1025))
            for _ in range(3)
        )
        try:
            case = setup_for(vertices)  # only legal non-empty RASTER inputs
        except AssertionError:
            continue
        case["attributes"] = attributes_for(len(cases), attr_rng)
        cases.append(case)

    max_covered = max(len(case["covered"]) for case in cases)
    lines = [
        "// Generated by generate_raster_walk_vectors.py; independent Python oracle.",
        f"localparam integer RASTER_WALK_CASES = {len(cases)};",
        f"localparam integer RASTER_WALK_MAX_COVERED = {max_covered};",
        "task automatic load_raster_walk_case(input integer idx);",
        "begin",
        "    walk_in_payload = '0;",
        "    expected_count = 0;",
        "    case (idx)",
    ]
    for idx, case in enumerate(cases):
        vertices = case["vertices"]
        deltas = case["deltas"]
        steps = case["steps"]
        initials = case["initials"]
        top = case["top"]
        covered = case["covered"]
        candidates = case["candidates"]
        attributes = case["attributes"]
        assert isinstance(vertices, tuple)
        lines += [f"        {idx}: begin"]
        lines += ["            walk_in_payload.classification = gfx_pkg::TRI_SETUP_RASTER;"]
        lines += [f"            walk_in_payload.tag = 16'h{int(case['tag']) & 0xffff:04x};"]
        lines += [f"            walk_in_payload.xmin = 9'd{case['xmin']};"]
        lines += [f"            walk_in_payload.xmax = 9'd{case['xmax']};"]
        lines += [f"            walk_in_payload.ymin = 8'd{case['ymin']};"]
        lines += [f"            walk_in_payload.ymax = 8'd{case['ymax']};"]
        for channel in ("r", "g", "b", "z"):
            start, dx, dy = attributes[channel]
            lines += [f"            walk_in_payload.{channel}_start = {sv32(start)};"]
            lines += [f"            walk_in_payload.{channel}_dx = {sv32(dx)};"]
            lines += [f"            walk_in_payload.{channel}_dy = {sv32(dy)};"]
        for edge, (dx, dy) in enumerate(deltas):
            lines += [f"            walk_in_payload.edge{edge}_dx = 16'sh{dx & 0xffff:04x};"]
            lines += [f"            walk_in_payload.edge{edge}_dy = 16'sh{dy & 0xffff:04x};"]
            lines += [f"            walk_in_payload.edge{edge}_step_x = {sv32(steps[edge][0])};"]
            lines += [f"            walk_in_payload.edge{edge}_step_y = {sv32(steps[edge][1])};"]
            lines += [f"            walk_in_payload.top_left[{edge}] = {1 if top[edge] else 0};"]
            lines += [f"            walk_in_payload.e{edge}_init = {sv32(initials[edge])};"]
        lines += [f"            expected_count = {len(covered)};"]
        for out_idx, (x, y) in enumerate(covered):
            lines += [f"            expected_x[{out_idx}] = 9'd{x}; expected_y[{out_idx}] = 8'd{y};"]
            for channel in ("r", "g", "b", "z"):
                start, dx, dy = attributes[channel]
                value = start + (x - case["xmin"]) * dx + (y - case["ymin"]) * dy
                assert -(1 << 41) <= value < (1 << 41)
                lines += [f"            expected_{channel}[{out_idx}] = {sv42(value)};"]
        lines += [f"            expected_candidates = {len(candidates)};"]
        lines += ["        end"]
    lines += [
        "        default: begin expected_count = 0; expected_candidates = 0; end",
        "    endcase",
        "end",
        "endtask",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    class_counts = {"covered": sum(bool(c["covered"]) for c in cases), "zero_covered": sum(not c["covered"] for c in cases)}
    print(f"generated={len(cases)} seed=0x9009 max_covered={max_covered} nonzero_cases={class_counts['covered']} zero_covered_cases={class_counts['zero_covered']}")


if __name__ == "__main__":
    generate()
